spring.application.name=back-end

# MySQL
spring.datasource.url=jdbc:mysql://172.21.210.95/cms?usessl=false
spring.datasource.username=root

spring.datasource.password=sSnMIWROHyS8PSbDDvHtQMSy
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MongoDB
spring.data.mongodb.uri=mongodb://root:3GAea0pmu721LF9knGguakCX@1172.21.169.109:27017/prescriptions?authSource=admin"

# MySQL JDBC driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

management.endpoint.health.show-details=always
management.health.db.enabled=true


api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M



spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false    
spring.thymeleaf.encoding=UTF-8